//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.MoHra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResolverCondition
    {
        public int Id { get; set; }
        public string Premise { get; set; }
        public int ConclusionResultId { get; set; }
        public string Desctipion { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Result ConclusionResult { get; set; }
    }
}
