//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.MoHra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResolverCondition
    {
        public int Id { get; set; }
        public string Premise { get; set; }
        public string Conclusion { get; set; }
        public string Desctipion { get; set; }
        public System.DateTime Created { get; set; }
    }
}
